### PR TITLE
upgraded typescript to the latest version 2.2

### PR DESCRIPTION
**Pull request by pgiemza**
Hello all,

Purpose of this PR is to upgrade typescript of example-app to the latest typescript version (2.2).

I am using established approach mentioned in the PR #88 by @MikeRyanDev 

Additionally I have added **EmptyAction** abstract class to deal with issues related with union of actions with and without payload.

If you agree with this **EmptyAction** solution then this class could be placed next to the **Action** interface in the **store** module :)

I hope that this will be helpful.

### CODE REVIEW

**Review by mxchange — APPROVED** [review]

**Review by krjordan — CHANGES_REQUESTED** [review]
Will you remove the `EmptyAction` class? This won't been needed once V4 is released.

**Comment by pgiemza** [comment]
Thanks for pointing this out :) 

I removed `EmptyAction` class and additionally I bumped angular to V4 to make sure that everything will work properly after applying changes of this atomic PR.

If I should do something more please let me know :)

**Comment by bypotatoes** [comment]
Could someone explain why `EmptyAction` won't been needed since V4? Tnx

**Comment by krjordan** [comment]
@bypotatoes The empty action won't be needed to union actions with and without payloads once v4 is released. It also doesn't provide consistency when implementing actions.

**Review by krjordan — APPROVED** [review]

**Comment by krjordan** [comment]
Closes #134

**Comment by chouclee** [comment]
@krjordan Are you saying Angular v4? #88 doesn't work for Angular 4 release version (yet)...

**Pull request merged**
