### PR TITLE
Upgraded angular-cli and karma config to @angular/cli

### PR DESCRIPTION
**Pull request by avatsaev**
angular-cli is deprecated, Angular Team is moving forward with @angular/cli from now on.

### CODE REVIEW

**Review by krjordan — CHANGES_REQUESTED** [review]
Can you update the `yarn.lock` file to include the angular-cli update? Once that is complete, I'll merge this in.

**Comment by avatsaev** [comment]
No problem

**Comment by avatsaev** [comment]
got Yarn error:

```
 An unexpected error occurred: "https://npm.americasarmy.com/source-map-support/-/source-map-support-0.4.10.tgz: connect ETIMEDOUT 10.4.5.47:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/avatsaev/DEV/Angular/example-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```


any idea?

**Comment by krjordan** [comment]
Just delete the `yarn.lock` file and recreate it. That should fix the issue.

**Comment by avatsaev** [comment]
done.

**Review by krjordan — APPROVED** [review]

**Pull request merged**
